language: node_js
node_js:
  - '8'
addons:
  firefox: latest
  chrome: stable
branches:
  only:
    - master
    - staging
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test -l chrome
