language: node_js
node_js:
  - "8"
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - yarn run lint
script:
  - xvfb-run yarn run test -l chrome